# Task 6 - Python Programming

1.Array

The NumPy (Numeric Python) package helps us manipulate large arrays and matrices of numeric data.

* To use the NumPy module, we need to import it using:
import numpy

* Arrays
A NumPy array is a grid of values. They are similar to lists, except that every element of an array must be the same type.

In [1]:
import numpy
def arrays(arr):
    return(numpy.array(arr[::-1], float))
arr = input('enter numbers :').strip().split(' ')
result = arrays(arr)
print(result)

enter numbers :1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


2.Shape and Reshape

In [4]:
import numpy
A = numpy.array(input('Enter space-separated numbers : ').split(),int)
A = A.reshape(3,3)
print(A)

Enter space-separated numbers : 1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


3.Transpose and Flatten

In [5]:
import numpy
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
A = numpy.array([input('Enter space-separated elements : ').split() for _ in range(N)],int) # Enter elements for each row. 
print(A.transpose())
print(A.flatten())

Enter space-separeted values of N and M : 2 2 
Enter space-separated elements : 1 2
Enter space-separated elements : 3 4
[[1 3]
 [2 4]]
[1 2 3 4]


4.Concatenate

In [6]:
import numpy
P,N,M = map(int, input('Enter space-separeted values of N and M and P : ').split())
A = numpy.array([input('Enter space-separated elements : ').split() for _ in range(P)],int)
B = numpy.array([input('Enter space-separated elements : ').split() for _ in range(N)],int)
C = numpy.concatenate((A,B),axis = 0)
print(C)

Enter space-separeted values of N and M and P : 4 3 2 
Enter space-separated elements : 1 2 
Enter space-separated elements : 1 2  
Enter space-separated elements : 1 2 
Enter space-separated elements : 1 2 
Enter space-separated elements : 3 4 
Enter space-separated elements : 3 4
Enter space-separated elements : 3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


5.Zeros and Ones

In [7]:
import numpy
A = tuple(map(int, input('Enter space-separeted values of X and Y and Z : ').split()))
print(numpy.zeros(A, int))
print(numpy.ones(A, int))

Enter space-separeted values of X and Y and Z : 3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


6.Eye and identity

In [8]:
import numpy
N,M = map(int, input('Enter space-separeted values of N and M : ').split())
print(numpy.eye(N,M))

Enter space-separeted values of N and M : 3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7.Array Mathematics

In [14]:
import numpy
N,M = map(int, input('Enter space-separeted values of M and N : ').split()) # N lines and M integer/line
A = numpy.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])
B = numpy.array([list(map(int, input('Enter space-separated elements : ').split())) for n in range(N)])

print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

Enter space-separeted values of M and N : 1 4 
Enter space-separated elements : 1 2 3 4 
Enter space-separated elements : 5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


8.Floor,Ceil and Rint

In [15]:
import numpy
A = numpy.array([list(map(float, input('Enter space-separated elements : ').split()))])
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

Enter space-separated elements : 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[[1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]]
[[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]]


9.Sum and Prod

In [16]:
import numpy
N, M = map(int, input('Enter space-separated values of N and M : ').split()) # N lines and M integers/line
A = numpy.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Sum = numpy.sum(A,axis = 0)
Prod = numpy.prod(Sum,axis = 0)
print(Prod)

Enter space-separated values of N and M : 2 2
Enter your numbers : 1 2
Enter your numbers : 3 4
24


10.Min and Max

In [17]:
import numpy
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = numpy.array([input('Enter your numbers : ').split() for _ in range(N)], int)
Min = numpy.min(A,axis = 1)
print(numpy.max(Min))

Enter space-separated values of N and M : 4 2 
Enter your numbers : 2 5 
Enter your numbers : 3 7 
Enter your numbers : 1 3 
Enter your numbers : 4 0
3


11.Mean, Var and Std

In [18]:
import numpy
N, M = map(int, input('Enter space-separated values of N and M : ').split())
A = numpy.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(numpy.mean(A,axis = 1))
print(numpy.var(A,axis = 0))
numpy.set_printoptions(legacy='1.13')
print(numpy.std(A))

Enter space-separated values of N and M : 2 2
Enter your numbers : 1 2
Enter your numbers : 3 4
[1.5 3.5]
[1. 1.]
1.11803398875


12.Dot and Cross

In [19]:
import numpy
N = int(input('Enter space-separeted values of N : ')) # N lines and M integer/line
A = numpy.array([input('Enter your numbers : ').split() for _ in range(N)], int)
B = numpy.array([input('Enter your numbers : ').split() for _ in range(N)], int)
print(numpy.dot(A,B))

Enter space-separeted values of N : 2
Enter your numbers : 1 2
Enter your numbers : 3 4 
Enter your numbers : 1 2
Enter your numbers : 3 4
[[ 7 10]
 [15 22]]


13.Inner and Outer

In [20]:
import numpy
A = numpy.array(input('Enter your numbers : ').split(),int)
B = numpy.array(input('Enter your numbers : ').split(),int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

Enter your numbers : 0 1
Enter your numbers : 2 3
3
[[0 0]
 [2 3]]


14.Polynomial

In [21]:
import numpy
A,B,C = map(float, input('Enter space-separated values of Coefficients : ').split())
X = int(input('Enter value of X  : ')) 
print(numpy.polyval([A,B,C],X))

Enter space-separated values of Coefficients : 1.1 2 3
Enter value of X  : 0
3.0


15.Linear Algebra

In [3]:
import numpy
N = int(input('Enter Value of N :'))
A = numpy.array([input('Enter Numbers :').split() for _ in range(N)], float)
print(round(numpy.linalg.det(A),2))

Enter Value of N :2
Enter Numbers :1.1 1.1
Enter Numbers :1.1 1.1
0.0
